modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/NEZNAMY/TAB/issues"
license = "Apache License Version 2.0"

[[mods]]
modId = "tab"
version = "5.4.0"
displayName = "TAB"
authors = "NEZNAMY"
credits = "@credits@"
description = '''An all-in-one solution that works'''
displayURL = "https://github.com/NEZNAMY/TAB"

[[dependencies.tab]]
modId = "forge"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "SERVER"

[[dependencies.tab]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.9],[1.21.10]"
ordering = "NONE"
side = "SERVER"
